#!/usr/bin/env python3
"""
FerPs Anonymous Bot - Interactive Setup Wizard
Helps configure the bot for first-time users
"""

import os
import sys
from pathlib import Path

def read_input(prompt, default=None):
    """Read input with optional default."""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "
    
    value = input(prompt).strip()
    return value if value else default

def main():
    print("\n" + "="*60)
    print("🤖 FerPS Anonymous Bot - Configuration Wizard")
    print("="*60 + "\n")
    
    env_file = Path(".env")
    
    # Check if .env exists
    if env_file.exists():
        print("✅ .env file already exists")
        overwrite = read_input("Overwrite existing .env?", "n").lower()
        if overwrite != "y":
            print("Keeping existing .env")
            return
    
    print("\n📋 Please provide the following information:\n")
    
    # Required: BOT_TOKEN
    print("1️⃣  BOT TOKEN (get from @BotFather on Telegram)")
    print("   https://t.me/BotFather -> /start -> /newbot")
    bot_token = read_input("   Bot Token")
    while not bot_token:
        bot_token = read_input("   Bot Token (required)")
    
    # Optional: Admin IDs
    print("\n2️⃣  ADMIN USER IDs (comma-separated)")
    print("   Get your ID from @userinfobot on Telegram")
    print("   You can add multiple: 123456789,987654321")
    admin_ids = read_input("   Admin IDs", "5821175466")
    
    # Webhook configuration
    print("\n3️⃣  WEBHOOK CONFIGURATION")
    mode = read_input("   Use webhooks (w) or polling (p)?", "w").lower()
    
    use_polling = "false"
    base_url = ""
    port = "8080"
    
    if mode == "p":
        use_polling = "true"
        base_url = "http://localhost:8080"
        print("   ✅ Polling mode selected (for local testing)")
    else:
        print("   Enter your public domain or ngrok URL")
        print("   Examples:")
        print("      https://yourdomain.com")
        print("      https://abc123.ngrok.io")
        base_url = read_input("   Base URL (required for webhooks)")
        while not base_url:
            base_url = read_input("   Base URL (required)")
        
        port = read_input("   Port (default 8080)", "8080")
        print("   ✅ Webhook mode selected")
    
    # Bot configuration
    print("\n4️⃣  BOT CONFIGURATION")
    channel = read_input("   Public channel (@name)", "@ferpsanonymous")
    
    # Optional: Database
    print("\n5️⃣  DATABASE & OTHER")
    db_path = read_input("   Database path", "data/anonymous.db")
    timezone = read_input("   Timezone", "UTC")
    
    # Generate .env content
    env_content = f"""# FerPs Anonymous Bot - Configuration
# Generated by setup wizard

# ============== REQUIRED ==============
BOT_TOKEN={bot_token}

# ============== WEBHOOK CONFIGURATION ==============
BASE_URL={base_url}
PORT={port}
USE_POLLING={use_polling}

# ============== BOT CONFIGURATION ==============
DEFAULT_CHANNEL={channel}
ADMIN_IDS={admin_ids}

# ============== DATABASE ==============
DB_PATH={db_path}

# ============== OPTIONAL ==============
TZ={timezone}
"""
    
    # Write .env file
    with open(".env", "w") as f:
        f.write(env_content)
    
    print("\n" + "="*60)
    print("✅ Configuration saved to .env")
    print("="*60 + "\n")
    
    # Summary
    print("📋 Configuration Summary:")
    print(f"   Bot Token: {'*' * (len(bot_token) - 4)}{bot_token[-4:]}")
    print(f"   Admin IDs: {admin_ids}")
    print(f"   Channel: {channel}")
    print(f"   Mode: {'Polling (local testing)' if use_polling == 'true' else 'Webhook (production)'}")
    if base_url:
        print(f"   Webhook URL: {base_url}/webhook/telegram")
    print(f"   Database: {db_path}")
    print(f"   Timezone: {timezone}")
    
    print("\n" + "="*60)
    print("🚀 Next Steps:")
    print("="*60 + "\n")
    
    if use_polling != "true":
        print("Webhook Setup:")
        print("  1. Make sure BASE_URL is publicly accessible and uses HTTPS")
        print("  2. Set up reverse proxy (nginx/Caddy) if needed")
        print("  See WEBHOOK_SETUP.md for detailed instructions")
    else:
        print("Local Testing (Polling):")
        print("  1. You can run the bot locally with polling")
        print("  No public domain needed - perfect for testing!")
    
    print("\nServer Setup:")
    print("  With Docker:")
    print("    docker-compose up -d")
    print("\nBot Setup in Telegram:")
    print("  1. Create an admin group (can be private)")
    print("  2. Add your bot to the group")
    print("  3. Run: /setgroup (in the admin group)")
    print("  4. Create a public channel")
    print("  5. Add bot to channel")
    print("  6. Run: /setchannel @channel_name (in admin group)")
    print("\n" + "="*60 + "\n")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled")
        sys.exit(1)
