#!/usr/bin/env python3
"""
FerPs Anonymous Bot - Interactive Setup Wizard
Helps configure the bot for first-time users
"""

import sys
from pathlib import Path

def read_input(prompt, default=None):
    """Read input with optional default."""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "
    
    value = input(prompt).strip()
    return value if value else default

def main():
    print("\n" + "="*60)
    print("🤖 FerPS Anonymous Bot - Configuration Wizard")
    print("="*60 + "\n")
    
    env_file = Path(".env")
    
    # Check if .env exists
    if env_file.exists():
        print("✅ .env file already exists")
        overwrite = read_input("Overwrite existing .env?", "n").lower()
        if overwrite != "y":
            print("Keeping existing .env")
            return
    
    print("\n📋 Please provide the following information:\n")
    
    # Required: BOT_TOKEN
    print("1️⃣  BOT TOKEN (get from @BotFather on Telegram)")
    print("   https://t.me/BotFather -> /start -> /newbot")
    bot_token = read_input("   Bot Token")
    while not bot_token:
        bot_token = read_input("   Bot Token (required)")
    
    # Optional: Admin IDs
    print("\n2️⃣  ADMIN USER IDs (comma-separated)")
    print("   Get your ID from @userinfobot on Telegram")
    print("   You can add multiple: 123456789,987654321")
    admin_ids = read_input("   Admin IDs", "5821175466")
    
    # Supabase configuration
    print("\n3️⃣  SUPABASE CONFIGURATION")
    supabase_url = read_input("   SUPABASE_URL")
    while not supabase_url:
        supabase_url = read_input("   SUPABASE_URL (required)")
    supabase_service_key = read_input("   SUPABASE_SERVICE_ROLE_KEY")
    while not supabase_service_key:
        supabase_service_key = read_input("   SUPABASE_SERVICE_ROLE_KEY (required)")

    # Webhook configuration
    print("\n4️⃣  WEBHOOK CONFIGURATION")
    print("   Enter your public domain or ngrok URL")
    print("   Examples:")
    print("      https://yourdomain.com")
    print("      https://abc123.ngrok.io")
    base_url = read_input("   Base URL (required for webhooks)")
    while not base_url:
        base_url = read_input("   Base URL (required)")
    
    port = read_input("   Port (default 8080)", "8080")
    print("   ✅ Webhook mode selected")
    
    # Bot configuration
    print("\n5️⃣  BOT CONFIGURATION")
    channel = read_input("   Public channel (@name)", "@ferpsanonymous")
    
    # Optional
    print("\n6️⃣  OPTIONAL")
    timezone = read_input("   Timezone", "UTC")
    
    # Generate .env content
    env_content = f"""# FerPs Anonymous Bot - Configuration
# Generated by setup wizard

# ============== REQUIRED ==============
BOT_TOKEN={bot_token}

# ============== SUPABASE ==============
SUPABASE_URL={supabase_url}
SUPABASE_SERVICE_ROLE_KEY={supabase_service_key}

# ============== WEBHOOK CONFIGURATION ==============
BASE_URL={base_url}
PORT={port}

# ============== BOT CONFIGURATION ==============
DEFAULT_CHANNEL={channel}
ADMIN_IDS={admin_ids}

# ============== OPTIONAL ==============
TZ={timezone}
"""
    
    # Write .env file
    with open(".env", "w") as f:
        f.write(env_content)
    
    print("\n" + "="*60)
    print("✅ Configuration saved to .env")
    print("="*60 + "\n")
    
    # Summary
    print("📋 Configuration Summary:")
    print(f"   Bot Token: {'*' * (len(bot_token) - 4)}{bot_token[-4:]}")
    print(f"   Admin IDs: {admin_ids}")
    print(f"   Channel: {channel}")
    masked_key = ("*" * (len(supabase_service_key) - 4) + supabase_service_key[-4:]) if len(supabase_service_key) > 4 else "*" * len(supabase_service_key)
    print(f"   Supabase URL: {supabase_url}")
    print(f"   Supabase Key: {masked_key}")
    print(f"   Mode: Webhook (production)")
    print(f"   Webhook URL: {base_url}/webhook/telegram")
    print(f"   Timezone: {timezone}")
    
    print("\n" + "="*60)
    print("🚀 Next Steps:")
    print("="*60 + "\n")
    
    print("Webhook Setup:")
    print("  1. Make sure BASE_URL is publicly accessible and uses HTTPS")
    print("  2. Set up reverse proxy (nginx/Caddy) if needed")
    print("  See WEBHOOK_SETUP.md for detailed instructions")
    
    print("\nServer Setup:")
    print("  With Docker:")
    print("    docker-compose up -d")
    print("\nBot Setup in Telegram:")
    print("  1. Create an admin group (can be private)")
    print("  2. Add your bot to the group")
    print("  3. Run: /setgroup (in the admin group)")
    print("  4. Create a public channel")
    print("  5. Add bot to channel")
    print("  6. Run: /setchannel @channel_name (in admin group)")
    print("\n" + "="*60 + "\n")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled")
        sys.exit(1)
