-- FerPS Anonymous Bot - Supabase PostgreSQL Schema
-- Run this in the Supabase SQL editor to create the tables

-- Settings table for storing configuration
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Moderation table for storing user submissions
CREATE TABLE IF NOT EXISTS moderation (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    username TEXT,
    first_name TEXT,
    last_name TEXT,
    message_type TEXT NOT NULL,
    content_text TEXT,
    media_file_id TEXT,
    channel_username TEXT NOT NULL,
    channel_message_id BIGINT NOT NULL,
    group_message_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Bans table for storing banned users
CREATE TABLE IF NOT EXISTS bans (
    user_id BIGINT PRIMARY KEY,
    reason TEXT,
    banned_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for better performance
CREATE INDEX IF NOT EXISTS idx_moderation_user_id ON moderation(user_id);
CREATE INDEX IF NOT EXISTS idx_moderation_created_at ON moderation(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_moderation_username ON moderation(username);
CREATE INDEX IF NOT EXISTS idx_moderation_channel_message ON moderation(channel_username, channel_message_id);
CREATE INDEX IF NOT EXISTS idx_bans_user_id ON bans(user_id);

-- Enable Row Level Security (optional, for added security)
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE moderation ENABLE ROW LEVEL SECURITY;
ALTER TABLE bans ENABLE ROW LEVEL SECURITY;

-- Create policies to allow service role full access (bot operations)
CREATE POLICY "Service role full access" ON settings
    FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Service role full access" ON moderation
    FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Service role full access" ON bans
    FOR ALL USING (auth.role() = 'service_role');

-- Create policy for anon users (limited read access if needed later)
CREATE POLICY "Anon read access" ON settings
    FOR SELECT USING (auth.role() = 'anon');
